DROP TABLE IF EXISTS "lh_site_configuration";
DROP TABLE IF EXISTS "lh_habit_2_tag";
DROP TABLE IF EXISTS "lh_task_2_tag";
DROP TABLE IF EXISTS "lh_tag";
DROP TABLE IF EXISTS "lh_habit_tracker";
DROP TABLE IF EXISTS "lh_habit";
DROP TABLE IF EXISTS "lh_task";
DROP TABLE IF EXISTS "lh_board_column";
DROP TABLE IF EXISTS "lh_board";
