// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BoardContent interface {
	IsBoardContent()
}

type Board struct {
	UserID        string         `json:"user_id"`
	Columns       []*Tag         `json:"columns"`
	ColumnContent []BoardContent `json:"column_content,omitempty"`
}

type Habbit struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Positive  bool   `json:"positive"`
	CreatedAt string `json:"createdAt"`
	UserID    string `json:"user_id"`
	Counter   int    `json:"counter"`
	Tags      []*Tag `json:"tags,omitempty"`
}

func (Habbit) IsBoardContent() {}

type Mutation struct {
}

type NewTask struct {
	Text string   `json:"text"`
	Tags []string `json:"tags,omitempty"`
}

type Query struct {
}

type Tag struct {
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UserID    string `json:"user_id"`
}

type Task struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Done       bool    `json:"done"`
	CreatedAt  string  `json:"createdAt"`
	FinishedAt *string `json:"finishedAt,omitempty"`
	UserID     string  `json:"user_id"`
	Tags       []*Tag  `json:"tags,omitempty"`
}

func (Task) IsBoardContent() {}
